In [179]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [180]:
# Import Data
# Clean Data
# Train_Test_Split
# EDA (Skip)
# Standardise Data
# Run Models
# Optimise Models
# Evaluate Models

In [184]:
#import database master 
df = pd.read_csv('nhanes_cleaned_01feb_2.csv')

##### Dropping The Redundant Columns

In [185]:
df.drop(columns = ['glycatedHb%',
'insulinumol',
'HbA1c',
 'Anaemia',
 'T1DM',
 'Known_T2DM',
 'insulin_prescribed',
 'bad_hba1c',
 'macrovascular_composite',
 'Doctor told you have diabetes',
 'Ever told you have prediabetes',
 'Ever told have health risk for diabetes',
 'Had blood tested past three years',
 'Taking insulin now',
 'How often check blood for glucose/sugar',
 'Past year times Dr check feet for sores',
 'How often do you check your feet', 'Unnamed: 0'],
inplace= True)

In [186]:
list(df.columns)

['SEQN',
 'Gender',
 'Age',
 'Other_Ethnicity',
 'Adult_Edu',
 'Marital_Status',
 'Pregnant',
 'Annual_household_income',
 'Annual_family_income',
 'Intake_day1_of_week',
 'Type_of_table_salt_used',
 'How_often_salt_added',
 'Salt_used_in_prep',
 'Weightloss_calorie_diet',
 'Lowfat_lowcholesteroldiet',
 'lowsaltdiet',
 'lowsugar',
 'lowfibre',
 'highfibre',
 'diabeticdiet',
 'weightgainmusclebuildingdiet',
 'lowcarbohydratediet',
 'glutenfreediet',
 'renalkidneydiet',
 'otherspecialdiet',
 'energykcal',
 'proteingm',
 'carbohydrategm',
 'totalsugargm',
 'dietfibregm',
 'totalfatgm',
 'totalsaturatedfattyacidsgm',
 'totalmonounsaturatedfattyacidsgm',
 'totalpolyunsaturatedfattyacidsgm',
 'cholesterolmg',
 'vitaminEmg',
 'retinol',
 'vitamina',
 'alphacarotene',
 'betacarotene',
 'betacryptoxanthin',
 'lycopene',
 'luteinzeaxanthin',
 'thiamineB1',
 'riboflavinB2',
 'niacin',
 'vitaminb6',
 'totalfolate',
 'folicacid',
 'foodfolate',
 'folatedfe',
 'totalcholine',
 'vitamineB12',
 'vitaminC',
 'vitamind2andd3',
 'vitaminK',
 'calcium',
 'phosphorus',
 'magnesium',
 'iron',
 'zinc',
 'copper',
 'sodium',
 'potassium',
 'selenium',
 'caffeine',
 'theobromine',
 'totalmoisture',
 'sfa4:0',
 'sfa6:0',
 'sfa8:0',
 'sfa10:0',
 'sfa12:0',
 'sfa14:0',
 'sfa16:0',
 'sfa18:0',
 'mfa16:1',
 'mfa18:1',
 'mfa20:1',
 'mfa22:1',
 'pfa18:2',
 'pfa18:3',
 'pfa18:4',
 'pfa20:4',
 'pfa20:5',
 'pfa22:6',
 'comparedtousualintake',
 'totalplainwaterdrankyesterdaygm',
 'totaltapwaterdrankyesterdaygm',
 'tapwatersource',
 'systolic_1',
 'diastolic_1',
 'systolic_2',
 'diastolic_2',
 'systolic_3',
 'diastolic_3',
 'weightkg',
 'bmi',
 'waistcircum',
 'avgsagittalabdodiameter',
 'hdl_mmol/l',
 'tchol_mmol/l',
 'Hbg/dL',
 'Albumin, refrigerated serum (g/dL)',
 'Alanine Aminotransferase (ALT) (U/L)',
 'Alkaline Phosphatase (ALP) (U/L)',
 'Aspartate Aminotransferase (AST) (U/L)',
 'Bicarbonate (mmol/L)',
 'Blood Urea Nitrogen (g/dL)',
 'Chloride (mmol/L)',
 'Cholesterol, refrigerated serum (mg/dL)',
 'Creatine Phosphokinase (CPK) (IU/L)',
 'Creatinine, refrigerated serum (mg/dL)',
 'Gamma Glutamyl Transferase (GGT) (U/L)',
 'Glucose, refrigerated serum (mg/dL)',
 'Iron, refrigerated serum (ug/dL)',
 'Lactate Dehydrogenase (LDH) (U/L)',
 'Phosphorus (mg/dL)',
 'Potassium (mmol/L)',
 'Sodium (mmol/L)',
 'Total Bilirubin (mg/dL)',
 'Total Calcium (mg/dL)',
 'Total Protein (g/dL)',
 'Triglycerides, refrig serum (mg/dL)',
 'Uric Acid (mg/dL)',
 'Ever told you had high blood pressure',
 'Told had high blood pressure - 2+ times',
 'Taking prescription for hypertension',
 'Now taking prescribed medicine for HBP',
 'Doctor told you - high cholesterol level',
 'Ever had blood cholesterol checked',
 'When blood cholesterol last checked',
 'Told to take prescriptn for cholesterol',
 'SP ever had pain or discomfort in chest',
 'Shortness of breath on stairs/inclines',
 'Money spent at supermarket/grocery store',
 'Money spent on food at other stores',
 'Money spent on eating out',
 'Money spent on carryout/delivered foods',
 'general_health_condition',
 'number of meals not home prepared',
 'number of meals from fast food or pizza place',
 'number of ready-to-eat foods in past 30 days',
 'number of frozen meals/pizza in past 30 days',
 'Dr told you were overweight',
 'Ever told you had coronary heart disease',
 'Ever told you had angina',
 'Ever told you had MI',
 'Ever told you had Stroke',
 'Close relative had MI',
 'Close relative had diabetes',
 'Dr told you to lose weight',
 'Dr told you to exercise',
 'Dr told you to reduce salt',
 'Dr told you to reduce calories',
 'days vigorous recreational activities',
 'minutes vigorous recreational activities',
 'days moderate recreational activities',
 'minutes moderate recreational activites',
 'minutes sedentary activity',
 'days physically active at least 60 mins',
 'hours watch tv or videos past 30 days',
 'hours use compuster past 30 days',
 'How do you consider your weight',
 'Self-reported weight - 1 yr ago (pounds)',
 'Tried to lose weight in past year',
 'Self-reported weight-10 yrs ago (pounds)',
 'Self-reported weight-age 25 (pounds)',
 'Self-reported greatest weight (pounds)',
 'Age when heaviest weight',
 'Prescriptions',
 'eGFR',
 'clinical_eGFR',
 'HbA1c_correct',
 'trig_mmol/l',
 'ldl_mmol/l',
 'avg_systolic',
 'avg_diastolic']

In [187]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43339 entries, 0 to 43338
Columns: 178 entries, SEQN to avg_diastolic
dtypes: float64(175), int64(2), object(1)
memory usage: 58.9+ MB

In [188]:
df.describe()

,SEQN,Gender,Age,Other_Ethnicity,Adult_Edu,Marital_Status,Pregnant,Annual_household_income,Annual_family_income,Intake_day1_of_week,...,Self-reported weight-age 25 (pounds),Self-reported greatest weight (pounds),Age when heaviest weight,eGFR,clinical_eGFR,HbA1c_correct,trig_mmol/l,ldl_mmol/l,avg_systolic,avg_diastolic
count,43339.000000,43339.000000,43339.000000,43339.000000,43278.000000,42912.000000,43339.000000,40628.000000,41426.000000,33113.000000,...,33286.000000,38285.000000,38083.000000,40713.000000,43339.000000,35111.000000,19649.000000,18906.000000,41552.000000,41346.000000
mean,49775.949030,1.504788,50.492374,3.057639,3.295069,2.414499,0.505319,8.122526,7.743639,4.442726,...,150.974464,192.878569,42.449203,95.508823,82.522187,38.641997,1.534313,3.004107,125.331697,70.866605
std,26456.765443,0.499983,17.793185,1.410374,1.307301,1.792427,0.886747,4.232656,4.272401,2.172549,...,37.279003,50.504128,16.845545,28.329937,13.063136,11.551191,1.369441,0.926380,19.497460,11.871546
min,2.000000,1.000000,21.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,50.000000,75.000000,7.000000,2.181060,2.181060,16.921732,0.158000,0.233000,64.666667,3.333333
25%,27920.500000,1.000000,36.000000,2.000000,2.000000,1.000000,0.000000,5.000000,4.000000,2.000000,...,125.000000,159.000000,28.000000,77.651829,78.678161,33.318758,0.858000,2.353000,112.000000,63.333333
50%,51266.000000,2.000000,50.000000,3.000000,3.000000,1.000000,0.000000,7.000000,7.000000,5.000000,...,145.000000,185.000000,40.000000,93.409172,90.000000,36.598164,1.231000,2.935000,122.000000,70.666667
75%,71485.500000,2.000000,65.000000,4.000000,4.000000,4.000000,0.000000,12.000000,12.000000,6.000000,...,170.000000,220.000000,55.000000,110.891826,90.000000,39.877569,1.818000,3.569000,135.333333,78.000000
max,93702.000000,2.000000,85.000000,7.000000,5.000000,6.000000,3.000000,15.000000,15.000000,7.000000,...,600.000000,600.000000,85.000000,394.911911,90.000000,181.985133,47.791000,16.266000,270.000000,132.000000

# Dropping All of the Redundant Columns and Np.NaN's

In [189]:
list(df.columns)

['SEQN',
 'Gender',
 'Age',
 'Other_Ethnicity',
 'Adult_Edu',
 'Marital_Status',
 'Pregnant',
 'Annual_household_income',
 'Annual_family_income',
 'Intake_day1_of_week',
 'Type_of_table_salt_used',
 'How_often_salt_added',
 'Salt_used_in_prep',
 'Weightloss_calorie_diet',
 'Lowfat_lowcholesteroldiet',
 'lowsaltdiet',
 'lowsugar',
 'lowfibre',
 'highfibre',
 'diabeticdiet',
 'weightgainmusclebuildingdiet',
 'lowcarbohydratediet',
 'glutenfreediet',
 'renalkidneydiet',
 'otherspecialdiet',
 'energykcal',
 'proteingm',
 'carbohydrategm',
 'totalsugargm',
 'dietfibregm',
 'totalfatgm',
 'totalsaturatedfattyacidsgm',
 'totalmonounsaturatedfattyacidsgm',
 'totalpolyunsaturatedfattyacidsgm',
 'cholesterolmg',
 'vitaminEmg',
 'retinol',
 'vitamina',
 'alphacarotene',
 'betacarotene',
 'betacryptoxanthin',
 'lycopene',
 'luteinzeaxanthin',
 'thiamineB1',
 'riboflavinB2',
 'niacin',
 'vitaminb6',
 'totalfolate',
 'folicacid',
 'foodfolate',
 'folatedfe',
 'totalcholine',
 'vitamineB12',
 'vitaminC',
 'vitamind2andd3',
 'vitaminK',
 'calcium',
 'phosphorus',
 'magnesium',
 'iron',
 'zinc',
 'copper',
 'sodium',
 'potassium',
 'selenium',
 'caffeine',
 'theobromine',
 'totalmoisture',
 'sfa4:0',
 'sfa6:0',
 'sfa8:0',
 'sfa10:0',
 'sfa12:0',
 'sfa14:0',
 'sfa16:0',
 'sfa18:0',
 'mfa16:1',
 'mfa18:1',
 'mfa20:1',
 'mfa22:1',
 'pfa18:2',
 'pfa18:3',
 'pfa18:4',
 'pfa20:4',
 'pfa20:5',
 'pfa22:6',
 'comparedtousualintake',
 'totalplainwaterdrankyesterdaygm',
 'totaltapwaterdrankyesterdaygm',
 'tapwatersource',
 'systolic_1',
 'diastolic_1',
 'systolic_2',
 'diastolic_2',
 'systolic_3',
 'diastolic_3',
 'weightkg',
 'bmi',
 'waistcircum',
 'avgsagittalabdodiameter',
 'hdl_mmol/l',
 'tchol_mmol/l',
 'Hbg/dL',
 'Albumin, refrigerated serum (g/dL)',
 'Alanine Aminotransferase (ALT) (U/L)',
 'Alkaline Phosphatase (ALP) (U/L)',
 'Aspartate Aminotransferase (AST) (U/L)',
 'Bicarbonate (mmol/L)',
 'Blood Urea Nitrogen (g/dL)',
 'Chloride (mmol/L)',
 'Cholesterol, refrigerated serum (mg/dL)',
 'Creatine Phosphokinase (CPK) (IU/L)',
 'Creatinine, refrigerated serum (mg/dL)',
 'Gamma Glutamyl Transferase (GGT) (U/L)',
 'Glucose, refrigerated serum (mg/dL)',
 'Iron, refrigerated serum (ug/dL)',
 'Lactate Dehydrogenase (LDH) (U/L)',
 'Phosphorus (mg/dL)',
 'Potassium (mmol/L)',
 'Sodium (mmol/L)',
 'Total Bilirubin (mg/dL)',
 'Total Calcium (mg/dL)',
 'Total Protein (g/dL)',
 'Triglycerides, refrig serum (mg/dL)',
 'Uric Acid (mg/dL)',
 'Ever told you had high blood pressure',
 'Told had high blood pressure - 2+ times',
 'Taking prescription for hypertension',
 'Now taking prescribed medicine for HBP',
 'Doctor told you - high cholesterol level',
 'Ever had blood cholesterol checked',
 'When blood cholesterol last checked',
 'Told to take prescriptn for cholesterol',
 'SP ever had pain or discomfort in chest',
 'Shortness of breath on stairs/inclines',
 'Money spent at supermarket/grocery store',
 'Money spent on food at other stores',
 'Money spent on eating out',
 'Money spent on carryout/delivered foods',
 'general_health_condition',
 'number of meals not home prepared',
 'number of meals from fast food or pizza place',
 'number of ready-to-eat foods in past 30 days',
 'number of frozen meals/pizza in past 30 days',
 'Dr told you were overweight',
 'Ever told you had coronary heart disease',
 'Ever told you had angina',
 'Ever told you had MI',
 'Ever told you had Stroke',
 'Close relative had MI',
 'Close relative had diabetes',
 'Dr told you to lose weight',
 'Dr told you to exercise',
 'Dr told you to reduce salt',
 'Dr told you to reduce calories',
 'days vigorous recreational activities',
 'minutes vigorous recreational activities',
 'days moderate recreational activities',
 'minutes moderate recreational activites',
 'minutes sedentary activity',
 'days physically active at least 60 mins',
 'hours watch tv or videos past 30 days',
 'hours use compuster past 30 days',
 'How do you consider your weight',
 'Self-reported weight - 1 yr ago (pounds)',
 'Tried to lose weight in past year',
 'Self-reported weight-10 yrs ago (pounds)',
 'Self-reported weight-age 25 (pounds)',
 'Self-reported greatest weight (pounds)',
 'Age when heaviest weight',
 'Prescriptions',
 'eGFR',
 'clinical_eGFR',
 'HbA1c_correct',
 'trig_mmol/l',
 'ldl_mmol/l',
 'avg_systolic',
 'avg_diastolic']

In [190]:
df = df.dropna(thresh=df.shape[0]*0.7,how='all',axis=1)

In [191]:
df = df.dropna()

In [192]:
df

,SEQN,Gender,Age,Other_Ethnicity,Adult_Edu,Marital_Status,Pregnant,Annual_household_income,Annual_family_income,Intake_day1_of_week,...,Self-reported weight - 1 yr ago (pounds),Tried to lose weight in past year,Self-reported weight-age 25 (pounds),Self-reported greatest weight (pounds),Age when heaviest weight,eGFR,clinical_eGFR,HbA1c_correct,avg_systolic,avg_diastolic
4,83737,2.0,72.0,1.0,2.0,4.0,0,14.0,14.0,6.0,...,150.0,2.0,150.0,150.0,72.0,49.298425,49.298425,40.970704,119.333333,58.666667
6,83742,2.0,32.0,1.0,4.0,1.0,2,6.0,6.0,7.0,...,125.0,1.0,118.0,130.0,20.0,123.135949,90.000000,37.691299,118.000000,70.666667
16,83767,2.0,54.0,6.0,4.0,3.0,0,14.0,14.0,6.0,...,126.0,2.0,110.0,130.0,54.0,89.717924,89.717924,43.156974,130.000000,79.333333
49,83837,2.0,45.0,1.0,2.0,1.0,0,14.0,14.0,5.0,...,170.0,2.0,120.0,180.0,35.0,173.414348,90.000000,93.441189,112.666667,68.000000
51,83844,1.0,27.0,1.0,2.0,6.0,0,7.0,7.0,6.0,...,150.0,2.0,150.0,159.0,27.0,123.248106,90.000000,31.132488,110.000000,66.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26884,51568,2.0,78.0,3.0,4.0,2.0,0,5.0,5.0,7.0,...,135.0,2.0,125.0,160.0,32.0,58.337358,58.337358,47.529515,173.333333,92.000000
26885,51569,2.0,56.0,3.0,3.0,5.0,0,3.0,3.0,7.0,...,150.0,1.0,115.0,155.0,46.0,102.024151,90.000000,36.598164,111.333333,70.000000
26887,51572,2.0,77.0,3.0,3.0,2.0,0,4.0,4.0,3.0,...,174.0,2.0,120.0,174.0,76.0,44.581082,44.581082,43.156974,160.000000,62.666667
26902,51593,2.0,64.0,3.0,4.0,1.0,0,14.0,14.0,2.0,...,195.0,1.0,140.0,200.0,63.0,86.676350,86.676350,40.970704,138.666667,78.000000
26903,51594,1.0,32.0,2.0,3.0,1.0,0,7.0,7.0,6.0,...,180.0,1.0,238.0,238.0,25.0,89.958644,89.958644,34.411893,127.333333,66.666667

------------------------------------------

# Assinging the target and X predictor matrices.

In [193]:
y = df.pop('HbA1c_correct')

In [194]:
X = df

In [195]:
# classification_problem = df['Known_T2DM']

------------------------------------------

# Performing a Train_Test_Split

In [196]:
from sklearn.model_selection import train_test_split

In [197]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

----------------------------------------------------------------------

# Standardizing Data

In [198]:
from sklearn.preprocessing import StandardScaler

In [199]:
scaler = StandardScaler()

In [200]:
X_train_std = scaler.fit_transform(X_train)

In [201]:
X_test_std = scaler.transform(X_test)

------------------------------------------------------------

In [202]:
X_train = pd.DataFrame(X_train_std, columns = X_train.columns)

In [203]:
X_test = pd.DataFrame(X_test_std, columns = X_test.columns)

------------------------------------------------------------------------------------

# Creating A RandomForrest Regressor

In [204]:
from sklearn.ensemble import RandomForestRegressor

In [205]:
rf_reg = RandomForestRegressor(n_estimators=250)

In [206]:
rf_reg.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=250,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [207]:
rf_reg.score(X_train,y_train)

0.9543921594604021

In [208]:
rf_reg.score(X_test,y_test)

0.602472227595853

In [209]:
from sklearn.model_selection import cross_val_score

In [210]:
np.mean(cross_val_score(rf_reg, X_train, y_train, cv=5))

0.6670135639624405

# Creating A RandomForrest Classifier

In [231]:
from sklearn.ensemble import RandomForestClassifier

In [232]:
df = pd.read_csv('nhanes_cleaned_01feb_2.csv')

In [233]:
class_df = df.copy()

In [234]:
class_df.drop(columns = ['glycatedHb%',
'insulinumol',
'HbA1c_correct',
'HbA1c',
 'Anaemia',
 'T1DM',
 'insulin_prescribed',
 'bad_hba1c',
 'macrovascular_composite',
 'Doctor told you have diabetes',
 'Ever told you have prediabetes',
 'Ever told have health risk for diabetes',
 'Had blood tested past three years',
 'Taking insulin now',
 'How often check blood for glucose/sugar',
 'Past year times Dr check feet for sores',
 'How often do you check your feet', 'Unnamed: 0'],
       
inplace= True)

In [235]:
class_df = class_df.dropna(thresh=df.shape[0]*0.6,how='all',axis=1)
class_df = class_df.dropna()

In [236]:
y = class_df.pop('Known_T2DM')

In [238]:
X = class_df

In [239]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [240]:
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)
######
X_train = pd.DataFrame(X_train_std, columns = X_train.columns)
X_test = pd.DataFrame(X_test_std, columns = X_test.columns)

In [249]:
clf = RandomForestClassifier(n_estimators = 100)

In [250]:
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [251]:
clf.score(X_test, y_test)

0.9230769230769231

In [252]:
clf.score(X_train, y_train)

1.0

In [253]:
cross_validated_scores = np.mean(cross_val_score(clf, X_test, y_test, cv=5))

In [254]:
cross_validated_scores

0.9231734693877552

In [256]:
X

,SEQN,Gender,Age,Other_Ethnicity,Adult_Edu,Marital_Status,Pregnant,Annual_household_income,Annual_family_income,Intake_day1_of_week,...,Self-reported weight - 1 yr ago (pounds),Tried to lose weight in past year,Self-reported weight-10 yrs ago (pounds),Self-reported weight-age 25 (pounds),Self-reported greatest weight (pounds),Age when heaviest weight,eGFR,clinical_eGFR,avg_systolic,avg_diastolic
15676,51654,1.0,66.0,3.0,4.0,1.0,0,6.0,6.0,6.0,...,165.0,2.0,165.0,155.0,169.0,64.0,46.530020,46.530020,115.333333,63.333333
15682,51661,2.0,60.0,1.0,3.0,1.0,0,7.0,7.0,7.0,...,150.0,2.0,170.0,140.0,180.0,59.0,83.778282,83.778282,122.666667,70.666667
15683,51662,2.0,44.0,1.0,2.0,1.0,2,15.0,15.0,7.0,...,155.0,1.0,150.0,130.0,190.0,30.0,80.492380,80.492380,129.333333,86.666667
15702,51692,1.0,54.0,2.0,5.0,3.0,0,9.0,9.0,6.0,...,280.0,1.0,270.0,200.0,290.0,53.0,97.192285,90.000000,91.333333,43.333333
15710,51704,1.0,54.0,1.0,1.0,1.0,0,9.0,9.0,6.0,...,185.0,2.0,185.0,178.0,185.0,45.0,120.913644,90.000000,121.333333,78.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26881,51560,1.0,68.0,4.0,3.0,1.0,0,14.0,14.0,6.0,...,250.0,2.0,240.0,175.0,250.0,68.0,93.560311,90.000000,117.333333,70.000000
26884,51568,2.0,78.0,3.0,4.0,2.0,0,5.0,5.0,7.0,...,135.0,2.0,150.0,125.0,160.0,32.0,58.337358,58.337358,173.333333,92.000000
26885,51569,2.0,56.0,3.0,3.0,5.0,0,3.0,3.0,7.0,...,150.0,1.0,150.0,115.0,155.0,46.0,102.024151,90.000000,111.333333,70.000000
26887,51572,2.0,77.0,3.0,3.0,2.0,0,4.0,4.0,3.0,...,174.0,2.0,150.0,120.0,174.0,76.0,44.581082,44.581082,160.000000,62.666667
26899,51590,1.0,52.0,3.0,4.0,1.0,0,15.0,15.0,1.0,...,215.0,1.0,220.0,200.0,230.0,40.0,76.312073,76.312073,104.000000,74.000000

In [258]:
from sklearn import metrics
from sklearn.metrics import classification_report

In [273]:
X

,SEQN,Gender,Age,Other_Ethnicity,Adult_Edu,Marital_Status,Pregnant,Annual_household_income,Annual_family_income,Intake_day1_of_week,...,Self-reported weight - 1 yr ago (pounds),Tried to lose weight in past year,Self-reported weight-10 yrs ago (pounds),Self-reported weight-age 25 (pounds),Self-reported greatest weight (pounds),Age when heaviest weight,eGFR,clinical_eGFR,avg_systolic,avg_diastolic
15676,51654,1.0,66.0,3.0,4.0,1.0,0,6.0,6.0,6.0,...,165.0,2.0,165.0,155.0,169.0,64.0,46.530020,46.530020,115.333333,63.333333
15682,51661,2.0,60.0,1.0,3.0,1.0,0,7.0,7.0,7.0,...,150.0,2.0,170.0,140.0,180.0,59.0,83.778282,83.778282,122.666667,70.666667
15683,51662,2.0,44.0,1.0,2.0,1.0,2,15.0,15.0,7.0,...,155.0,1.0,150.0,130.0,190.0,30.0,80.492380,80.492380,129.333333,86.666667
15702,51692,1.0,54.0,2.0,5.0,3.0,0,9.0,9.0,6.0,...,280.0,1.0,270.0,200.0,290.0,53.0,97.192285,90.000000,91.333333,43.333333
15710,51704,1.0,54.0,1.0,1.0,1.0,0,9.0,9.0,6.0,...,185.0,2.0,185.0,178.0,185.0,45.0,120.913644,90.000000,121.333333,78.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26881,51560,1.0,68.0,4.0,3.0,1.0,0,14.0,14.0,6.0,...,250.0,2.0,240.0,175.0,250.0,68.0,93.560311,90.000000,117.333333,70.000000
26884,51568,2.0,78.0,3.0,4.0,2.0,0,5.0,5.0,7.0,...,135.0,2.0,150.0,125.0,160.0,32.0,58.337358,58.337358,173.333333,92.000000
26885,51569,2.0,56.0,3.0,3.0,5.0,0,3.0,3.0,7.0,...,150.0,1.0,150.0,115.0,155.0,46.0,102.024151,90.000000,111.333333,70.000000
26887,51572,2.0,77.0,3.0,3.0,2.0,0,4.0,4.0,3.0,...,174.0,2.0,150.0,120.0,174.0,76.0,44.581082,44.581082,160.000000,62.666667
26899,51590,1.0,52.0,3.0,4.0,1.0,0,15.0,15.0,1.0,...,215.0,1.0,220.0,200.0,230.0,40.0,76.312073,76.312073,104.000000,74.000000

In [262]:
y_pred = clf.predict(X_test)
y_true = y_test

In [265]:
print(classification_report(y_true, y_pred, 
                            target_names=['class 0', 'class_1']
                           ))

              precision    recall  f1-score   support

     class 0       0.00      0.00      0.00        19
     class_1       0.92      1.00      0.96       228

    accuracy                           0.92       247
   macro avg       0.46      0.50      0.48       247
weighted avg       0.85      0.92      0.89       247

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [267]:
from sklearn.metrics import confusion_matrix

In [272]:
confusion_matrix(y_true, y_pred)

array([[  0,  19],
       [  0, 228]])

In [ ]:
# Doing SMOTE
# Try re-running the models
# Play around with the threshold probabilities
# Feature importances for decision trees
# Plot (y_true vs y_pred plot for the regressor model)
# Linear regression model with LassoCV() to see which features have the most linear assosiations with the target
# Grid_searching different types of models
## Randomforest, svm_regressor,

### To add data for text modelling with a classifier you can do this:
- Use PCA to reduce the dimensionality as 1 extra word will be 1 extra column.
- Use sparse matrices to do your model fit, rather than dense matrices if the columns are too wide.

--------------------------------------------------------

### Post_Project - Use Frequency - https://www.kdnuggets.com/2018/01/managing-machine-learning-workflows-scikit-learn-pipelines-part-3.html